//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTransaction
    {
        public int payTransactionId { get; set; }
        public int studentPayTransactionId { get; set; }
        public decimal payAmount { get; set; }
        public System.DateTime payDate { get; set; }
    
        public virtual StudentPayTransaction StudentPayTransaction { get; set; }
    }
}
