//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodStatu
    {
        public int periodStatusId { get; set; }
        public int periodId { get; set; }
        public int periodStatusTypeId { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
