//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodGradeStudentTranTypeConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodGradeStudentTranTypeConfiguration()
        {
            this.StudentPayTransactions = new HashSet<StudentPayTransaction>();
        }
    
        public int periodGradeStudentTranTypeConfigurationId { get; set; }
        public int periodGradeStudentId { get; set; }
        public int transactionTypeId { get; set; }
        public decimal payConfiguration { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public int runScheduleId { get; set; }
    
        public virtual PeriodGradeStudent PeriodGradeStudent { get; set; }
        public virtual RunSchedule RunSchedule { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayTransaction> StudentPayTransactions { get; set; }
    }
}
