//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPayTransactionStatu
    {
        public int studentPayTransactionStatusId { get; set; }
        public int studentPayTransactionId { get; set; }
        public int payTransactionStatusTypeId { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
    
        public virtual PayTransactionStatusType PayTransactionStatusType { get; set; }
        public virtual StudentPayTransaction StudentPayTransaction { get; set; }
    }
}
